// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbit.Api.Data;

#nullable disable

namespace Orbit.Api.Migrations
{
    [DbContext(typeof(OrbitDbContext))]
    partial class OrbitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Orbit.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CheckupMissaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CHECKUP_MISSAO_ID");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("NIVEL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("CheckupMissaoId");

                    b.ToTable("ALERTA", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.Astronauta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("Fadiga")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FADIGA");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("FUNCAO");

                    b.Property<int>("Hidratacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HIDRATACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Oxigenacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OXIGENACAO");

                    b.Property<decimal>("TemperaturaCorporal")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("TEMPERATURA_CORPORAL");

                    b.HasKey("Id");

                    b.ToTable("ASTRONAUTA", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.BaseEspacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("Agua")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AGUA");

                    b.Property<int>("Energia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ENERGIA");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<int>("Medicamentos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEDICAMENTOS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Oxigenio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OXIGENIO");

                    b.Property<int>("PecasManutencao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PECAS_MANUTENCAO");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS_OPERACIONAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("BASE_ESPACIAL", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.CheckupMissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CRIADO_EM");

                    b.Property<int>("MissaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MISSAO_ID");

                    b.Property<int>("PontuacaoRisco")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PONTUACAO_RISCO");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("RECOMENDACAO");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("RESULTADO");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId");

                    b.ToTable("CHECKUP_MISSAO", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int?>("BaseSuporteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BASE_SUPORTE_ID");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESTINO");

                    b.Property<int>("NaveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NAVE_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("OBJETIVO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("BaseSuporteId");

                    b.HasIndex("NaveId");

                    b.ToTable("MISSAO", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.MissaoAstronauta", b =>
                {
                    b.Property<int>("MissaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MISSAO_ID");

                    b.Property<int>("AstronautaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ASTRONAUTA_ID");

                    b.Property<string>("PapelNaMissao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("PAPEL_NA_MISSAO");

                    b.HasKey("MissaoId", "AstronautaId");

                    b.HasIndex("AstronautaId");

                    b.ToTable("MISSAO_ASTRONAUTA", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.Nave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CombustivelBateria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("COMBUSTIVEL_BATERIA");

                    b.Property<string>("ComunicacaoOk")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("COMUNICACAO_OK");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS_OPERACIONAL");

                    b.Property<decimal>("TemperaturaSistema")
                        .HasPrecision(5, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("TEMPERATURA_SISTEMA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("NAVE", (string)null);
                });

            modelBuilder.Entity("Orbit.Api.Models.Alerta", b =>
                {
                    b.HasOne("Orbit.Api.Models.CheckupMissao", "CheckupMissao")
                        .WithMany("Alertas")
                        .HasForeignKey("CheckupMissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckupMissao");
                });

            modelBuilder.Entity("Orbit.Api.Models.CheckupMissao", b =>
                {
                    b.HasOne("Orbit.Api.Models.Missao", "Missao")
                        .WithMany("Checkups")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("Orbit.Api.Models.Missao", b =>
                {
                    b.HasOne("Orbit.Api.Models.BaseEspacial", "BaseSuporte")
                        .WithMany("MissoesComoSuporte")
                        .HasForeignKey("BaseSuporteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbit.Api.Models.Nave", "Nave")
                        .WithMany("Missoes")
                        .HasForeignKey("NaveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseSuporte");

                    b.Navigation("Nave");
                });

            modelBuilder.Entity("Orbit.Api.Models.MissaoAstronauta", b =>
                {
                    b.HasOne("Orbit.Api.Models.Astronauta", "Astronauta")
                        .WithMany("Missoes")
                        .HasForeignKey("AstronautaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbit.Api.Models.Missao", "Missao")
                        .WithMany("Astronautas")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronauta");

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("Orbit.Api.Models.Astronauta", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("Orbit.Api.Models.BaseEspacial", b =>
                {
                    b.Navigation("MissoesComoSuporte");
                });

            modelBuilder.Entity("Orbit.Api.Models.CheckupMissao", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Orbit.Api.Models.Missao", b =>
                {
                    b.Navigation("Astronautas");

                    b.Navigation("Checkups");
                });

            modelBuilder.Entity("Orbit.Api.Models.Nave", b =>
                {
                    b.Navigation("Missoes");
                });
#pragma warning restore 612, 618
        }
    }
}
